# Site settings
title: Michael Espey
email: michael@maespey.com
description: > # this means to ignore newlines until "baseurl:"
  I am currently a student at Luther College in Decorah Iowa.
  I am working on my Undergrad in Computer Science.<br />
  This is mainly just a place for me to play around with
  to practice.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maespey.com" # the base hostname & protocol for your site
twitter_username: 19_MAE_94
github_username:  espemi01

# Build settings
markdown: kramdown
