title:            Michael Espey
description:      all about M.E.
disqus_shortname: maespey
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:              http://maespey.com

# Owner/author information
owner:
  name:           Michael Espey
  avatar:         avatar.jpg
  bio:            "I am a 20 year old Luther College student."
  email:          michael@maespey.com
  twitter:        19_MAE_94
  facebook:       loading.michael
  github:         espemi01
  stackexchange:  
  linkedin:       pub/michael-espey/a6/592/223
  instagram:      m_espey
  flickr:         espemi01

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics: UA-59294223-1
google_verify:      
bing_verify:       

jekyll-archives:
  enabled:
    - tags
    - year
  layouts:
    year: year_index
    tag: tag_index
  permalinks:
    year: /:year/
    tag: /tag/:name/

timezone:    America/Chicago
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

permalink:   /:categories/:title/

paginate: 5
paginate_path: "/blog/page:num/"
paginate_alt: "/projects/page:num/"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]